name: clean_voila_env
channels:
  - defaults
  - conda-forge
dependencies:
  - pip
  - voila
  - numpy
  - matplotlib
  - scikit-learn
  - ipykernel
  - ipywidgets
  - tensorflow=2.10.0
  - pip:
    - tensorflow-text==2.10.0 # always update version number to tensorflow version
